project:
  type: website

website:
  title: "Leo Hung Trung Nguyen"
  navbar:
    left:
      - text: "About Me"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: lux
    toc: false
    smooth-scroll: true
    page-layout: full
    css: styles.css

website:
  page-footer:
    left: "Â© 2025 Leo Hung Nguyen"
    right: "Built with Quarto"



