project:
  type: website

website:
  title: "Leo Hung Nguyen"
  navbar:
    left:
      - text: "About You"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    left: |
      Â© 2025 Leo Hung Nguyen  
      <button id="dark-toggle" class="dark-toggle-btn">ðŸŒ’ Toggle Dark Mode</button>
    right: "Built with Quarto"

format:
  html:
    theme: lux
    toc: false
    smooth-scroll: true
    page-layout: full
    css:
      - styles.css
      - darkmode.css
    include-after-body:
      - darkmode.js

