project:
  type: website

website:
  title: "Leo Hung Nguyen"
  navbar:
    left:
      - text: "About You"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: false
    smooth-scroll: true
    page-layout: full
    css: styles.css




